import type { Product } from "../domain/product"

export const seedProducts: Product[] = [
  {
    id: "P001",
    name: "Manzana Roja",
    sku: "FRV-0001",
    price: 1.2,
    cost: 0.7,
    manejaStock: true,
    stock: 320,
    stockMinimum: 50,
    unit: "kg",
    supplier: "Frutas del Valle",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P002",
    name: "Plátano",
    sku: "FRV-0002",
    price: 0.95,
    cost: 0.5,
    manejaStock: true,
    stock: 0,
    stockMinimum: 40,
    unit: "kg",
    supplier: "Frutas del Valle",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P003",
    name: "Tomate",
    sku: "FRV-0003",
    price: 1.8,
    cost: 1.0,
    manejaStock: true,
    stock: -3,
    stockMinimum: 30,
    unit: "kg",
    supplier: "Huerta Local",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P004",
    name: "Leche Entera 1L",
    sku: "LAC-0011",
    price: 1.1,
    cost: 0.75,
    manejaStock: false,
    stock: null,
    stockMinimum: 60,
    unit: "u",
    supplier: "Lácteos San José",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P005",
    name: "Yogur Natural 500g",
    sku: "LAC-0012",
    price: 1.5,
    cost: 0.9,
    manejaStock: true,
    stock: 12,
    stockMinimum: 25,
    unit: "u",
    supplier: "Lácteos San José",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P006",
    name: "Queso Manchego 250g",
    sku: "LAC-0013",
    price: 4.5,
    cost: 2.8,
    manejaStock: true,
    stock: 64,
    stockMinimum: 20,
    unit: "u",
    supplier: "Quesería Aurora",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P007",
    name: "Pechuga de Pollo",
    sku: "CAR-0021",
    price: 6.2,
    cost: 4.0,
    manejaStock: true,
    stock: 80,
    stockMinimum: 25,
    unit: "kg",
    supplier: "Avícola Norte",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P008",
    name: "Carne Molida Res",
    sku: "CAR-0022",
    price: 7.8,
    cost: 5.2,
    manejaStock: true,
    stock: 6,
    stockMinimum: 20,
    unit: "kg",
    supplier: "Cárnicos del Sur",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P009",
    name: "Pan de Molde",
    sku: "PAN-0031",
    price: 2.1,
    cost: 1.1,
    manejaStock: true,
    stock: 130,
    stockMinimum: 40,
    unit: "u",
    supplier: "Horno Dorado",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P010",
    name: "Baguette",
    sku: "PAN-0032",
    price: 1.4,
    cost: 0.6,
    manejaStock: true,
    stock: 75,
    stockMinimum: 30,
    unit: "u",
    supplier: "Horno Dorado",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P011",
    name: "Agua Mineral 1.5L",
    sku: "BEB-0041",
    price: 0.85,
    cost: 0.4,
    manejaStock: true,
    stock: 420,
    stockMinimum: 100,
    unit: "u",
    supplier: "Manantial Claro",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P012",
    name: "Refresco Cola 2L",
    sku: "BEB-0042",
    price: 2.3,
    cost: 1.3,
    manejaStock: true,
    stock: 210,
    stockMinimum: 80,
    unit: "u",
    supplier: "Distribuidora Andes",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P013",
    name: "Jugo de Naranja 1L",
    sku: "BEB-0043",
    price: 2.6,
    cost: 1.5,
    manejaStock: true,
    stock: 9,
    stockMinimum: 30,
    unit: "u",
    supplier: "Frutas del Valle",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P014",
    name: "Detergente 3kg",
    sku: "LIM-0051",
    price: 8.9,
    cost: 5.5,
    manejaStock: true,
    stock: 60,
    stockMinimum: 15,
    unit: "u",
    supplier: "QuímicaPro",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P015",
    name: "Papel Higiénico 12u",
    sku: "LIM-0052",
    price: 6.5,
    cost: 3.8,
    manejaStock: true,
    stock: 140,
    stockMinimum: 40,
    unit: "u",
    supplier: "Celulosa Plus",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P016",
    name: "Arroz 1kg",
    sku: "DES-0061",
    price: 1.7,
    cost: 1.0,
    manejaStock: true,
    stock: 300,
    stockMinimum: 80,
    unit: "u",
    supplier: "Granos del Campo",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P017",
    name: "Aceite de Oliva 1L",
    sku: "DES-0062",
    price: 9.4,
    cost: 6.2,
    manejaStock: true,
    stock: 48,
    stockMinimum: 20,
    unit: "u",
    supplier: "Olivar Real",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P018",
    name: "Pasta Espagueti 500g",
    sku: "DES-0063",
    price: 1.3,
    cost: 0.7,
    manejaStock: true,
    stock: 4,
    stockMinimum: 50,
    unit: "u",
    supplier: "Granos del Campo",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P019",
    name: "Helado Vainilla 1L",
    sku: "CON-0071",
    price: 4.2,
    cost: 2.5,
    manejaStock: true,
    stock: 70,
    stockMinimum: 20,
    unit: "u",
    supplier: "FríoMax",
    promotions: null,
    storePromotions: null,
  },
  {
    id: "P020",
    name: "Verduras Mixtas 1kg",
    sku: "CON-0072",
    price: 3.1,
    cost: 1.8,
    manejaStock: true,
    stock: 55,
    stockMinimum: 20,
    unit: "u",
    supplier: "FríoMax",
    promotions: null,
    storePromotions: null,
  },
]
